# Generated by Django 5.1.6 on 2025-03-11 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissaince', models.DateTimeField()),
                ('tel', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^6\\d{8}$', 'entrez un numero au format CMR')])),
                ('email', models.EmailField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='images_articles')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id_compte', models.BigAutoField(primary_key=True, serialize=False)),
                ('solde', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamybank.client')),
            ],
        ),
        migrations.CreateModel(
            name='Compte_Epargne',
            fields=[
                ('compte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wamybank.compte')),
                ('id_compteE', models.BigAutoField(primary_key=True, serialize=False)),
                ('taux_interet', models.IntegerField()),
            ],
            bases=('wamybank.compte',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_trans', models.CharField(max_length=30)),
                ('etat', models.BooleanField(choices=[(True, 'SUCCES'), (False, 'ECHEC')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.IntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wamybank.client')),
            ],
        ),
    ]
