# Generated by Django 5.1.6 on 2025-03-11 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamybank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='id_compte',
            field=models.BigAutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='compte_epargne',
            name='id_compteE',
            field=models.BigAutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
