# Generated by Django 5.1.6 on 2025-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamybank', '0003_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_naissaince',
            field=models.DateField(),
        ),
    ]
