# Generated by Django 5.1.6 on 2025-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesarticles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
